ob-f/OpenBot

body/README.md
=> Fix STL link

policy/dataloader.py, policy/policy_learning.ipynb
- Updated the Juypter notebook and dataloader to make them compatible with Windows
- Minor refactoring to make the training process a little bit more transparent
=> Windows bugfix

body/README_CN.md
The average price of the switch is around 0.4 Yuan
=> Cheaper switch

firmware/openbot_v1_nano/openbot_v1_nano.ino
Setting this to 0 allows building code without installing the NewPing
library.
Signed-off-by: Shane Loretz <shane.loretz@gmail.com>
=> Add HAS_SONAR definition

firmware/openbot_v1_nano/openbot_v1_nano.ino
- several improvements to make code more readable and compact
- removed NewPing due to many reported issues (e.g. interference on pin 8, pin 3 and 11 not usable as PWM, etc.)
- implemented interrupt based ultrasonic sensor readings
- implemented interrupt based speed sensor readings for all hardware configurations
- all main features/sensors can enabled/disabled with flags so the firmware only contains the functionalities needed and is as fast and extensible as possible
- improved NO_PHONE_MODE
=> major firmware update

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/org/openbot/CameraActivity.java, android/app/src/main/java/org/openbot/NsdService.java, android/app/src/main/java/org/openbot/UploadService.java, policy/README.md, policy/server/README.md, policy/server/main.py, policy/server/openbot/__init__.py, policy/server/openbot/api.py, policy/server/openbot/gif.py, policy/server/openbot/preview.py, policy/server/openbot/upload.py, policy/server/openbot/zeroconf.py, policy/server/requirements.txt, policy/server/templates/index.html
simple python HTTP server for log uploading
zeroconf added to the server for auto-discovery if connected to the same network
see Issue #120
Preview
=> WIP: Web server for log uploading

android/app/src/main/java/org/openbot/robot/CameraActivity.java
Seems to have gotten broken in the refactor commit a8e831e0f8617e3ed47b995805d350dd7a665966
=> Fix setting drive mode from UI

policy/requirements.txt
=> Issue #152

android/app/src/main/java/org/openbot/main/ControlsFragment.java, android/app/src/main/java/org/openbot/robot/CameraActivity.java
phone controller event observer wasn't observing events on different screens. disposing it on every destroy instance seems to fix this
=> dispose obverver on destroy

android/app/ContributionGuide.md, android/app/README.md, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/org/openbot/OpenBotApplication.java, android/app/src/main/java/org/openbot/ai/AIFragment.java, android/app/src/main/java/org/openbot/common/Constants.java, android/app/src/main/java/org/openbot/common/FeatureList.java, android/app/src/main/java/org/openbot/env/GameController.java, android/app/src/main/java/org/openbot/env/NearbyConnection.java, android/app/src/main/java/org/openbot/env/UsbConnection.java, android/app/src/main/java/org/openbot/env/Vehicle.java, android/app/src/main/java/org/openbot/logging/LoggerFragment.java, android/app/src/main/java/org/openbot/main/ControlsFragment.java, android/app/src/main/java/org/openbot/main/MainActivity.java, android/app/src/main/java/org/openbot/main/SettingsFragment.java, android/app/src/main/java/org/openbot/robot/CameraActivity.java, android/app/src/main/java/org/openbot/robot/DefaultActivity.java, android/app/src/main/java/org/openbot/robot/FreeRoamFragment.java, android/app/src/main/java/org/openbot/robot/LegacyCameraConnectionFragment.java, android/app/src/main/res/layout-land/fragment_ai.xml, android/app/src/main/res/layout-land/fragment_logger.xml, android/app/src/main/res/layout/fragment_ai.xml, android/app/src/main/res/layout/fragment_logger.xml
• Prevent app re-opening on USB connection
• USB connection/disconnection real time listener
• Enable Noise- WIP
• Retain phone controller connection on screen timeout
=> Refactor 2 WIP

android/app/src/main/java/org/openbot/ai/AIFragment.java, android/app/src/main/java/org/openbot/common/CameraFragment.java, android/app/src/main/java/org/openbot/common/ControlsFragment.java, android/app/src/main/java/org/openbot/logging/LoggerFragment.java, android/app/src/main/java/org/openbot/original/CameraActivity.java, android/app/src/main/java/org/openbot/robot/FreeRoamFragment.java, android/app/src/main/res/layout-land/fragment_ai.xml, android/app/src/main/res/layout/fragment_ai.xml
prevent model closure on screen timeout
=> fix thread closure on screent timeout

android/app/src/main/java/org/openbot/autopilot/AutopilotFragment.java, android/app/src/main/java/org/openbot/env/ImageUtils.java
[Fix for this issue](https://github.com/intel-isl/OpenBot/issues/209)
=> App crashes in Autopilot fragment, when Autopilot switch is activated

android/app/src/main/java/org/openbot/autopilot/AutopilotFragment.java, android/app/src/main/java/org/openbot/env/ImageUtils.java, android/app/src/main/java/org/openbot/objectNav/ObjectNavFragment.java
Fix for issue [#211 ](https://github.com/intel-isl/OpenBot/issues/211)
=> Fix app crash in object tracking fragment (Android 6)

android/app/src/main/java/org/openbot/logging/SensorListAdapter.java, android/app/src/main/java/org/openbot/logging/SensorsDialog.java, android/app/src/main/res/layout-land/dialog_sensors.xml, android/app/src/main/res/layout/dialog_sensors.xml, android/app/src/main/res/values/strings.xml
select all button for sensors, and scroll bar
=> add select all button for sensor list

android/app/src/main/java/org/openbot/env/GameController.java, firmware/openbot_nano/openbot_nano.ino
- More responsive control
- Clean up the code
=> Refactor game controller refactor

android/app/README.md, android/app/src/main/java/org/openbot/objectNav/ObjectNavFragment.java, android/app/src/main/java/org/openbot/utils/MovingAverage.java
- add benchmarking results
- add benchmarking code
=> Object nav benchmarking

CONTRIBUTING.md, body/diy/README_CN.md
fix some link errors at CONTRIBUTING.md and body/diy/README_CN.md
=> fix link errors

python/.gitignore, python/README.md, python/download_data.py, python/export_openvino.py, python/generate_data_for_training.py, python/infer.py, python/joystick.py, python/realsense.py, python/requirements.txt, python/run.py, python/tests/get_test_data.sh, python/tests/test_download_data.py, python/tests/test_export_openvino.py, python/tests/test_generate_data.py, python/tests/test_infer.py, python/tests/test_joystick.py, python/tests/test_motor.py, python/tests/test_realsense.py
- Control of robot through Python
- Generating motor control signals via (1) joystick or (2) trained policy
- Data collection by controlling robot via joystick
- Support for Realsense D435i camera
- Support for Xbox One controller
- Inference backends: Tensorflow, TFlite, OpenVino (for supported hardware only), PyTorch (by converting PyTorch->ONNX->OpenVino)
=> Control and inference via Python for OpenBot

android/app/src/main/java/org/openbot/robot/RobotInfoFragment.java, firmware/openbot/openbot.ino
=> Support RTR TT2 in firmware

policy/openbot/utils.py, policy/policy_learning.ipynb
Matplotlib running with interactive backend causes issues when running the webserver due to threading.
=> Bugfix webserver

controller/node-js/README.md
The Node.js Controller works for windows too. Tried and tested multiple times on different browsers, works like a charm! Updating the README file in the controller -> Node.js file. Tested on Windows, Updating the documentation.
=> OpenBot Node.js Controller

android/controller/build.gradle, android/robot/build.gradle, android/robot/src/main/java/org/openbot/modelManagement/ModelManagementFragment.java
fixed tflite issue in model management
=> fix model management

android/comlib/build.gradle, android/comlib/download.gradle, android/robot/build.gradle
This is a test for the build pipeline.
=> Fix USB Serial Depreciation error

firmware/openbot/openbot.ino
=> Fix wrong right rpm on the OLED display.
